import Link from 'next/link';
import '../globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const styles = {
  wrapper: {
    display: 'flex',
    FlexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
    FlexWrap: 'wrap',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div style={styles.wrapper} className='bg-gray-800 text-blue-500'>
          <Link className='m-4 text-blue-800' href='/myaccount'>
            {' '}
            Go to My Account page{' '}
          </Link>
          <Link className='m-4 text-blue-800' href='/about'>
            {' '}
            ≈ About page
          </Link>
          <Link className='m-4 text-blue-800' href='/products'>
            {' '}
            ≈ Products page
          </Link>
          <Link className='m-4 text-blue-800' href='/login'>
            {' '}
            ≈ Login page
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
