import Link from 'next/link';
import '../globals.css';
import Script from 'next/script';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const styles = {
  wrapper: {
    display: 'flex',
    FlexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
    FlexWrap: 'wrap',
  },
};

const links = [
  { href: '/', label: 'Home' },
  { href: '/docs', label: 'Docs' },
  { href: '/about', label: 'About' },
  { href: '/myaccount', label: 'My Account' },
  { href: '/products', label: 'Products' },
  { href: '/login', label: 'Login' },
  { href: '/place-order', label: 'Order' },
  { href: '/complex-dashboard', label: 'Complex-dashboard' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css'
          integrity='sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN'
          crossOrigin='anonymous'
        />
      </head>
      <body>
        <div style={styles.wrapper} className='p-4 bg-gray-800 text-blue-500'>
          {links.map((link) => {
            return (
              <Link href={link.href} key={link.label}>
                {link.label}
              </Link>
            );
          })}
        </div>
        <div className='container'>{children}</div>
        <Script
          src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js'
          integrity='sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+'
          crossOrigin='anonymous'
        />
        <Script
          src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js'
          integrity='sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL'
          crossOrigin='anonymous'
        />
      </body>
    </html>
  );
}
